language: java
jdk: oraclejdk8

script:
  - mvn clean verify -f alma-server/pom.xml -e
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "KHEasma"
      - git config --local user.email "asma.khelifi@outlook.fr"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
    deploy:
      provider: releases
      api_key: "GITHUB OAUTH TOKEN"
      file: "FILE TO UPLOAD"
      skip_cleanup: true